name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.1.2

    - name: Make Gradlew Executable
      run: chmod +x ./gradlew

    - name: Set JAVA_HOME
      run: |
        echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
        echo "PATH=$JAVA_HOME_17_X64/bin:$PATH" >> $GITHUB_ENV

    - name: Build with Gradle
      run: |
        java -version
        ./gradlew build --stacktrace

    - name: Run Tests
      run: ./gradlew test --stacktrace
